
# Owners Code of Conduct {#code-of-conduct}

## Conduct

### Franchise owners must act with the best interest of their team in mind at ALL times!

#### The exact punishment will be determined and handed by a joint decision made by the Commissioner and the Senior Council.
    
### Collusion will __NOT__ be tolerated

#### Collusion does not include unofficial league discussions between team owners
    
#### Collusion shall apply to issues where any number of teams work together, in an illegal fashion, to harm the interest of another team(s)
        
##### Standard trade vetoes are exempt from this rule
          
###### Unless gifts or any type of offering to persuade a vote is offered
            
##### Illegal may include such things as: blackmail, bribery, threat to do harm to owner(s) or their loved ones, or possessions, etc.
        
#### Any team owner may call for an official review of any event that they feel to fall within the above stated definition of collusion.
    
##### The owner who calls for the review does not have to be an involved party
        
##### If a review is requested, the Senior Council will be called upon to do three things
        
###### Listen to the case of ALL involved parties
            
###### Take a vote (majority rules) on whether collusion occurred as it is stated in the above definitions.
###### If collusion is proven, it will be then become the task of the Senior Council, along with the Commissioner, to decide on and impose a proper punishment on all convicted parties.

### Cheating of all types will not be tolerated

#### If a team or teams is caught and proven to be cheating, via any method that provides an unfair advantage or disadvantage for any team, they will face punishment from the Senior Council and/or Commissioner.
    
### At minimum, owners who “quit” on their team at any point during the season (including the playoffs) will face a mandatory 1 year ban (minimum) from the league.
    
#### A two-thirds vote of the league is required to reinstate a banned member.
    
#### An official ruling to determine if an owner has “quit” on their team will be made by a majority vote of the Senior Council.
    
##### If a ruling is made during the season (including playoffs) a replacement owner may be voted in and allowed to take full control of the abandoned team.