# Ties

## Weekly

### In the unlikely event of a head to head weekly tie, the team whose kicker scored the most points in the week of play will be awarded the win.

### If a tie remains after the kicker comparison there will be a coin toss between the two teams to determine the winner.
#### The toss will be called in the air by the team who has the most total cumulative points for the season.
#### If the tie happens in the first week of the season or the teams have the same amount of cumulative points, the team with the lower first round draft pick from the current seasons draft will make the in-air call of the coin.
#### The commissioner will toss the coin.
#### The coin toss will be at a location of the commissioners choosing; involved parties do not need to be present for the toss. Speakerphone or video chat will be used for communication between the parties and the commissioner.

### If the coin lands on an edge and the tie remains, there will be a fight to the death on the dawn of the next Wednesday.
#### A new team owner will be selected to manage the abandoned team via the procedures outlined in this document

## End of Season
### Please refer to the Playoffs section for information on end of season ties between two or more teams.