# Trades


## Eligibility

### Trades are allowed between franchise owners and can include two or more teams. 

### Active NFL players are the only tradable commodity in TSU.
#### Money, draft picks, personal & sexual favors, etc., are NOT tradable commodities and any trade including such will be considered null and void.

### All trades will be open to votes of approval or disapproval from the entire league.

### For a trade to be overruled, and thus canceled, it must receive at least 6 votes of disapproval from uninvolved team owners. 

### Trades will NOT be allowed once the playoffs begin. NO Exceptions!

### Short term trade backs will not be tolerated

### ALL trades not involving the commissioner are subject to a final review by the commissioner, without regard to the league vote. 



## Who, What, Why, Where, & When

### Trades may be proposed and accepted at any time prior to the trade deadline but, unless special circumstances apply, will be processed by the commissioner only after a minimum wait time of 24 hours, in which all involved players must be and remain in an “unlocked” status.
#### During this 24 hour period other teams may vote to approve or disapprove of the trade.
#### Trades will only be processed if the players status is “unlocked”, meaning they have not yet played in their weekly game.


### The commissioner has the power to review and approve or disapprove of any trade, where a conflict of interest does not exist for the commissioner, in any time frame he or she wishes without the 6 vote approval or 24 hour waiting period.
#### This power should only be used in special circumstances where the normal procedure may be unfair due to circumstances that are unforeseen at this time.