# Offseason Changes


## When
### Rule changes and league updates will take place in the official TSU offseason.
#### The official offseason runs from the day following the TSU Championship game until the day prior to the draft. 

### The only way a rule change may be made during the season is if a motion to change a rule is made to the commissioner, who will then inform ALL team owners and ask for a “yay” or “nay” vote from all league members.  In-season rule changes can only be passed with a unanimous vote of all members.


## Who and How

### Rule or changes of any type may be suggested at any point by any team owner.

### All suggestions for offseason changes will be recorded by the commissioner and all topics will be discussed and voted on by all eligible members during the offseason period.

### Approved changes will be added to the Constitution and will appear in the Articles as well as in the Amendments section. 

### Only team owners who have completed a full season of play in TSU are eligible to vote on league rule changes.

#### Teams must also be current active members of the league to be eligible for voting.
#### All active team owners, including owners who have not completed a full season in TSU, are eligible to vote on in-season rule changes.
#### The commissioner may include or exclude non-tenured members on any vote he/she deems necessary for such action. 

### Rule changes that deal solely with the INTERNAL functions of the league (i.e., veto limits, roster size, etc.) require a majority vote to alter.

### Rule changes that deal solely with EXTERNAL functions of the league (i.e., increase in number of teams, entry fee alteration, webhost, etc.,) require a 2/3 of all eligible members.


## Adding A New Owner

### In the event an owner spot opens in TSU, the following processes will be followed in order to fill the vacancy.
#### Out of season (not expelled or banished in-season)
##### Potential members must be nominated by an existing member of TSU; these nominating members will be referred to as sponsors.
##### Potential members will be required to take the official Saturated Unicorn Entrance Exam (SUEE) and each candidate will be discussed by their sponsor and the Senior Council. 
##### The nominee with the highest cumulative score from the SUEE and Senior Council review will be offered a spot in TSU.
###### The Commissioner will make the official offer of membership to the potential member.
###### Sponsors will be responsible for informing their individual nominees who were not granted membership 


### In-season (owner quit, was expelled, banished etc.)

#### Due to the weekly constraints of fantasy football, the person finishing 2nd in the most recent nominee process will be asked to take over for the departed team owner.
#### The new owner will take the team as it was left and will be expected to manage the team to the best of their abilities. 
#### An in-season invitation is not a permanent owner position and all owners added in-season will be evaluated, by the Senior Council, based on many factors, including their handling of the in-season takeover of the abandoned team.
##### The Senior Council may ask for input from the league when evaluating a prospective member under these circumstances.



## New Membership Requirements & Expectations
### The sponsor of a nominee who becomes a member of TSU will be assigned several duties and responsibilities. They are as follows:
#### Ensure the nominees entry fee and any other dues are paid on time 
#### Ensure the nominee sets a valid line-up each week
#### Ensure the nominee follows all rules and standards of TSU fantasy football league, both written and understood. 

### If the nominee fails at participate in TSU at an expected level the sponsor will face the following punishments:
#### If a nominee does not pay their money on time their sponsor has 1 week to get the funds to the commissioner.  Failure to do so will result in the forfeiture of the members own league entry fee and membership in TSU. 
#### If a nominee fails to submit a valid weekly lineup the sponsor will be penalized 10 FAAB bucks or 10% of their remaining balance, whichever is greater. 
#### Punishment for any other violation or action deemed to be harmful to the league or league owner, by a nominee, will be fully discussed and handed down by the Senior Council.


## Inactive Status & Priority Reentry

### If a tenured (completed a full year of play-draft to conclusion of season) owner needs to leave the league for any reason they will be able to reenter the league, (within 3 years) with a preferred status, at a later date.
#### The departing member must notify the commissioner of their intentions to leave the league (a reason would not need to be disclosed)
#### The member must be in good standing (not quitting on their team or committing other behavior deemed detrimental to the league)
#### The member must depart during a period of the season that allows for possible adjustments by the league (this could include a 2 week notice if during the season, any time in the off-season (until August 1st) as this would allow ample time to find a replacement.

### If a member qualifies for this status they will be able to go into an “inactive” league status that would grant them the ability to assume the top spot on the waiting list (if within 3 years) and bypass the entrance exam.

### The member WOULD have to apply for reentry and their status would be voted on by all tenured league members.  If the owners departure is temporary (ex. They have an emergency and can’t complete a season) then a temporary owner may take over for the persons team until they are ready to return. 

### Unless otherwise specified, a “temporary” owner would become permanent if during this period, they manage a single team for a complete season (finish the season started by the tenured owner, then complete the next season, draft through championship).  In this instance the “temporary” owner would be up for a full league membership vote and the “tenured” member would be at the top of the waiting list but would be required to wait until an owner vacates their spot in TSU.

### It will be up to the departing member and the replacement owner to make arrangements related to entry fees, winnings and potential trophy branding.  The Commissioner will act is a mediator for these discussions and must be notified of the final arrangements made by the owners.