# Amendments

## 2020 Recorded Amendments
1. Increased entry fee to $215
1. Modified defensive scoring (added base 5, and -0.25 per point allowed)
1. Modified playoff structure to ensure teams making round 2 of the playoffs can not enter The Randy Bowl
1. Added 1 additional IR spot for this year only


## 2019 Recorded Amendments
1. Change to full auction draft 
1. Update defense and special teams scoring
1. Christian de Caestecker replaced Colby Mattie
1. Update the league fees to \$140
1. Britt Elmore took over sole managership from the previously co-mangaged team with Christian Wiberley
1. Update membership rules to never allow a fan of Alabama, Florida or Ohio State into the league
1. Update roster requirements to add conditions for owners who are acting in the best interest of their team by not starting a full 9 man roster

## 2018 Recorded Amendments
1. Change to trial run for hybrid auction draft 
1. Penalty for failing to draft complete and valid roster
1. Accidental drop rule
1. Update the league fees to $130
1. Record understood rule that all members are responsible for 1/12 of draft cost each year 
1. Cleanup of end of season tie language
1. Christian de Caestecker replaced by Jordan Rudolph as alternate Senior Council member
1. Christian de Caestecker replaced by Christian Wiberley & Britt Elmore as one year co-managers in The Saturated Unicorn.

## 2017 Recorded Amendments
1. Update the league fees to $125 
1. Add inactive status for tenured members
1. Update the end of season tie procedures 
1. Add succession of Senior Council for voting
1. No owner changes

## 2016 Recorded Amendments
1. Change league size to 12 members (Mathew and Jordan added)
1. Jon Hawker replaces Jeff Giles
1. Update payouts to reflect the two extra members
1. Detailed plan for end of season ties (season record ties)
1. Addition of alternate Senior Council member (Christian)

## 2015 Recorded Amendments
1. Updated playoff structure 
1. Increase entry fee to $110 + $10
1. FAAB for Free Agency
1. Volunteer for The Randy – The Hunger Games Clause 
1. Institute time limit between draft picks
1. Impose ban on players that miss two consecutive drafts 

## 2014 Recorded Amendments
1. Increase entry fee from $50.00 to $75.00 (external)
1. Define the parameters of collusion 
1. Increase the veto limit from 4 votes to 6 votes
1. Change to an offline draft
1. Put a 1 season voting restriction on new members
1. End season with week 16 of the NFL season
1. 2nd round of playoffs becomes a 1 week single elimination game
1. Create rule disallowing short term trade backs 
1. Outline the differences for external vs. internal rule changes and create required vote counts for each 
1. Change 1.5 point bonus for 50+ yard td reception or rush to 0. (Standard Scoring)
1. Eliminate divisions
1. Play each team at least once
1. Implement the Colby winning system for a 1 year trial period
1. Waiver position is a tradable commodity
1. TSU playoffs end at week 16 – The Peyton Manning Rule
1. Set draft order by selecting playing cards